/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 *
    https://github.com/chuyrc/EstructurasGUI.git
 */
package gui;

import java.awt.Color;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author chuy
 */
public class PanelPP extends javax.swing.JPanel {

    Stack<Integer> pila = new Stack();
    
    public PanelPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarBc = new javax.swing.JPanel();
        ingresarBtn = new javax.swing.JLabel();
        extraerBc = new javax.swing.JPanel();
        extraerBtn = new javax.swing.JLabel();
        topeBc = new javax.swing.JPanel();
        topeBtn = new javax.swing.JLabel();
        buscarBc = new javax.swing.JPanel();
        buscarBtn = new javax.swing.JLabel();
        limpiarBc = new javax.swing.JPanel();
        limpiarBtn = new javax.swing.JLabel();
        infoBc = new javax.swing.JPanel();
        infoBtn = new javax.swing.JLabel();
        mostrarBc = new javax.swing.JPanel();
        mostrarBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 255));

        ingresarBc.setBackground(new java.awt.Color(51, 51, 255));

        ingresarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        ingresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ingresarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresarBtn.setText("Ingresar dato");
        ingresarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresarBcLayout = new javax.swing.GroupLayout(ingresarBc);
        ingresarBc.setLayout(ingresarBcLayout);
        ingresarBcLayout.setHorizontalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        ingresarBcLayout.setVerticalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        extraerBc.setBackground(new java.awt.Color(51, 51, 255));

        extraerBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        extraerBtn.setForeground(new java.awt.Color(255, 255, 255));
        extraerBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extraerBtn.setText("Extraer dato");
        extraerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extraerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extraerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extraerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extraerBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extraerBcLayout = new javax.swing.GroupLayout(extraerBc);
        extraerBc.setLayout(extraerBcLayout);
        extraerBcLayout.setHorizontalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraerBcLayout.createSequentialGroup()
                .addComponent(extraerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        extraerBcLayout.setVerticalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extraerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        topeBc.setBackground(new java.awt.Color(51, 51, 255));

        topeBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        topeBtn.setForeground(new java.awt.Color(255, 255, 255));
        topeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topeBtn.setText("Mostrar tope");
        topeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout topeBcLayout = new javax.swing.GroupLayout(topeBc);
        topeBc.setLayout(topeBcLayout);
        topeBcLayout.setHorizontalGroup(
            topeBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topeBcLayout.setVerticalGroup(
            topeBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        buscarBc.setBackground(new java.awt.Color(51, 51, 255));

        buscarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarBtn.setText("Buscar dato");
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarBcLayout = new javax.swing.GroupLayout(buscarBc);
        buscarBc.setLayout(buscarBcLayout);
        buscarBcLayout.setHorizontalGroup(
            buscarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        buscarBcLayout.setVerticalGroup(
            buscarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        limpiarBc.setBackground(new java.awt.Color(51, 51, 255));

        limpiarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        limpiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limpiarBtn.setText("Limpiar pila");
        limpiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout limpiarBcLayout = new javax.swing.GroupLayout(limpiarBc);
        limpiarBc.setLayout(limpiarBcLayout);
        limpiarBcLayout.setHorizontalGroup(
            limpiarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limpiarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        limpiarBcLayout.setVerticalGroup(
            limpiarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        infoBc.setBackground(new java.awt.Color(51, 51, 255));

        infoBtn.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        infoBtn.setForeground(new java.awt.Color(255, 255, 255));
        infoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBtn.setText("?");
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout infoBcLayout = new javax.swing.GroupLayout(infoBc);
        infoBc.setLayout(infoBcLayout);
        infoBcLayout.setHorizontalGroup(
            infoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        infoBcLayout.setVerticalGroup(
            infoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mostrarBc.setBackground(new java.awt.Color(51, 51, 255));

        mostrarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        mostrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        mostrarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarBtn.setText("Mostrar pila");
        mostrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostrarBcLayout = new javax.swing.GroupLayout(mostrarBc);
        mostrarBc.setLayout(mostrarBcLayout);
        mostrarBcLayout.setHorizontalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        mostrarBcLayout.setVerticalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(topeBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ingresarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mostrarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpiarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(extraerBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(infoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extraerBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topeBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseEntered
        ingresarBc.setBackground(new Color(102,102,255));
        ingresarBtn.setForeground(Color.black);
    }//GEN-LAST:event_ingresarBtnMouseEntered

    private void ingresarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseExited
        ingresarBc.setBackground(new Color(51,51,255));
        ingresarBtn.setForeground(Color.white);
    }//GEN-LAST:event_ingresarBtnMouseExited

    private void extraerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseEntered
        extraerBc.setBackground(new Color(102,102,255));
        extraerBtn.setForeground(Color.black);
    }//GEN-LAST:event_extraerBtnMouseEntered

    private void extraerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseExited
        extraerBc.setBackground(new Color(51,51,255));
        extraerBtn.setForeground(Color.white);
    }//GEN-LAST:event_extraerBtnMouseExited

    private void topeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topeBtnMouseEntered
        topeBc.setBackground(new Color(102,102,255));
        topeBtn.setForeground(Color.black);
    }//GEN-LAST:event_topeBtnMouseEntered

    private void topeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topeBtnMouseExited
        topeBc.setBackground(new Color(51,51,255));
        topeBtn.setForeground(Color.white);
    }//GEN-LAST:event_topeBtnMouseExited

    private void buscarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseEntered
        buscarBc.setBackground(new Color(102,102,255));
        buscarBtn.setForeground(Color.black);
    }//GEN-LAST:event_buscarBtnMouseEntered

    private void buscarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseExited
        buscarBc.setBackground(new Color(51,51,255));
        buscarBtn.setForeground(Color.white);
    }//GEN-LAST:event_buscarBtnMouseExited

    private void ingresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseClicked
        try {
            pila.push(Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese el dato")));
            JOptionPane.showMessageDialog(this,"Se ingreso el dato con exito");
        }catch(NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_ingresarBtnMouseClicked

    private void extraerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseClicked
        if(pila.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La lista esta vacia");
            
            return;
        }
        int a = pila.pop();
        JOptionPane.showMessageDialog(this,"Se extrajo el tope de la pila: " + a);
    }//GEN-LAST:event_extraerBtnMouseClicked

    private void topeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topeBtnMouseClicked
        if(pila.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La lista esta vacia");
            
            return;
        }
        try {
            int a = pila.peek();
            JOptionPane.showMessageDialog(this,"El tope de la pila es: " + a);
        }catch(NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_topeBtnMouseClicked

    private void buscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseClicked
        if(pila.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La lista esta vacia");
            
            return;
        }
        try {
            int a = Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese el elemento a buscar"));
            int b = pila.search(a);
            if(b != -1)
                JOptionPane.showMessageDialog(this,"El elemento " + a + " esta en la pila");
            else
                JOptionPane.showMessageDialog(this,"El elemento " + a + " no esta en la pila");
        }catch(NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_buscarBtnMouseClicked

    private void limpiarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarBtnMouseEntered
        limpiarBc.setBackground(new Color(102,102,255));
        limpiarBtn.setForeground(Color.black);
    }//GEN-LAST:event_limpiarBtnMouseEntered

    private void limpiarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarBtnMouseExited
        limpiarBc.setBackground(new Color(51,51,255));
        limpiarBtn.setForeground(Color.white);
    }//GEN-LAST:event_limpiarBtnMouseExited

    private void limpiarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarBtnMouseClicked
        pila.clear();
        JOptionPane.showMessageDialog(this,"Se ha limpiado la pila");
    }//GEN-LAST:event_limpiarBtnMouseClicked

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        JOptionPane.showMessageDialog(this,"STACK (pila)\n"
            + "   Métodos\n"
            + "       Ingresar dato -> Ingresa un dato al Stack\n"
            + "       Extraer dato -> Obtiene y elimina el tope de la pila (ultimo dato)\n"
            + "       Mostrar dato -> Muestra el tope de la pila (ultimo dato)\n"
            + "       Eliminar dato -> Elimina un elemento de una posición\n"
            + "       Buscar dato -> Verefica si el dato dado esta en la pila\n"
            + "       Limpiar lista -> Limpia el Stack\n"
            + " **Este Stack es de tipo Integer por lo que solo admite números enteros,\n cualquier otro tipo de dato no será tomado en cuenta**\n");
    }//GEN-LAST:event_infoBtnMouseClicked
    
    private void infoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseEntered
        infoBc.setBackground(new Color(102,102,255));
        infoBtn.setForeground(Color.black);
    }//GEN-LAST:event_infoBtnMouseEntered

    private void infoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseExited
        infoBc.setBackground(new Color(51,51,255));
        infoBtn.setForeground(Color.white);
    }//GEN-LAST:event_infoBtnMouseExited

    private void mostrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseClicked
        if(pila.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La pila esta vacia");
            return;
        }
        String lista = "";
        String listaInvertida = "";
        for(int dato : pila) {
            lista += "  " + dato + "\n";
        }
        String[] cadena = lista.split(" ");
        
        for(int i = cadena.length - 1; i >= 0; i--) {
                listaInvertida += "" + cadena[i];
        }
        JOptionPane.showMessageDialog(this,"Pila\n" + listaInvertida);
    }//GEN-LAST:event_mostrarBtnMouseClicked

    private void mostrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseEntered
        mostrarBc.setBackground(new Color(102,102,255));
        mostrarBtn.setForeground(Color.black);
    }//GEN-LAST:event_mostrarBtnMouseEntered

    private void mostrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseExited
        mostrarBc.setBackground(new Color(51,51,255));
        mostrarBtn.setForeground(Color.white);
    }//GEN-LAST:event_mostrarBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buscarBc;
    private javax.swing.JLabel buscarBtn;
    private javax.swing.JPanel extraerBc;
    private javax.swing.JLabel extraerBtn;
    private javax.swing.JPanel infoBc;
    private javax.swing.JLabel infoBtn;
    private javax.swing.JPanel ingresarBc;
    private javax.swing.JLabel ingresarBtn;
    private javax.swing.JPanel limpiarBc;
    private javax.swing.JLabel limpiarBtn;
    private javax.swing.JPanel mostrarBc;
    private javax.swing.JLabel mostrarBtn;
    private javax.swing.JPanel topeBc;
    private javax.swing.JLabel topeBtn;
    // End of variables declaration//GEN-END:variables
}
