/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 *
    https://github.com/chuyrc/EstructurasGUI.git
 */
package gui;

import estructuras.Cola;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author chuy
 */
public class PanelCS extends javax.swing.JPanel {

    Cola cola = new Cola();
    
    public PanelCS() {
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarBc = new javax.swing.JPanel();
        ingresarBtn = new javax.swing.JLabel();
        extraerBc = new javax.swing.JPanel();
        extraerBtn = new javax.swing.JLabel();
        mostrarBc = new javax.swing.JPanel();
        mostrarBtn = new javax.swing.JLabel();
        vaciarBc = new javax.swing.JPanel();
        vaciarBtn = new javax.swing.JLabel();
        infoBc = new javax.swing.JPanel();
        infoBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 255));

        ingresarBc.setBackground(new java.awt.Color(51, 51, 255));

        ingresarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        ingresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ingresarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresarBtn.setText("Ingresar dato");
        ingresarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresarBcLayout = new javax.swing.GroupLayout(ingresarBc);
        ingresarBc.setLayout(ingresarBcLayout);
        ingresarBcLayout.setHorizontalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        ingresarBcLayout.setVerticalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        extraerBc.setBackground(new java.awt.Color(51, 51, 255));

        extraerBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        extraerBtn.setForeground(new java.awt.Color(255, 255, 255));
        extraerBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extraerBtn.setText("Extraer dato");
        extraerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extraerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extraerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extraerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extraerBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extraerBcLayout = new javax.swing.GroupLayout(extraerBc);
        extraerBc.setLayout(extraerBcLayout);
        extraerBcLayout.setHorizontalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraerBcLayout.createSequentialGroup()
                .addComponent(extraerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        extraerBcLayout.setVerticalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extraerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        mostrarBc.setBackground(new java.awt.Color(51, 51, 255));

        mostrarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        mostrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        mostrarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarBtn.setText("Mostrar cola");
        mostrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostrarBcLayout = new javax.swing.GroupLayout(mostrarBc);
        mostrarBc.setLayout(mostrarBcLayout);
        mostrarBcLayout.setHorizontalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mostrarBcLayout.setVerticalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        vaciarBc.setBackground(new java.awt.Color(51, 51, 255));

        vaciarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        vaciarBtn.setForeground(new java.awt.Color(255, 255, 255));
        vaciarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaciarBtn.setText("Vaciar cola");
        vaciarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vaciarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaciarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vaciarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vaciarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout vaciarBcLayout = new javax.swing.GroupLayout(vaciarBc);
        vaciarBc.setLayout(vaciarBcLayout);
        vaciarBcLayout.setHorizontalGroup(
            vaciarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaciarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        vaciarBcLayout.setVerticalGroup(
            vaciarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaciarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        infoBc.setBackground(new java.awt.Color(51, 51, 255));

        infoBtn.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        infoBtn.setForeground(new java.awt.Color(255, 255, 255));
        infoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBtn.setText("?");
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout infoBcLayout = new javax.swing.GroupLayout(infoBc);
        infoBc.setLayout(infoBcLayout);
        infoBcLayout.setHorizontalGroup(
            infoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        infoBcLayout.setVerticalGroup(
            infoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(extraerBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vaciarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(infoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(infoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extraerBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vaciarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseEntered
        ingresarBc.setBackground(new Color(102,102,255));
        ingresarBtn.setForeground(Color.black);
    }//GEN-LAST:event_ingresarBtnMouseEntered

    private void ingresarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseExited
        ingresarBc.setBackground(new Color(51,51,255));
        ingresarBtn.setForeground(Color.white);
    }//GEN-LAST:event_ingresarBtnMouseExited

    private void extraerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseEntered
        extraerBc.setBackground(new Color(102,102,255));
        extraerBtn.setForeground(Color.black);
    }//GEN-LAST:event_extraerBtnMouseEntered

    private void extraerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseExited
        extraerBc.setBackground(new Color(51,51,255));
        extraerBtn.setForeground(Color.white);
    }//GEN-LAST:event_extraerBtnMouseExited

    private void mostrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseEntered
        mostrarBc.setBackground(new Color(102,102,255));
        mostrarBtn.setForeground(Color.black);
    }//GEN-LAST:event_mostrarBtnMouseEntered

    private void mostrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseExited
        mostrarBc.setBackground(new Color(51,51,255));
        mostrarBtn.setForeground(Color.white);
    }//GEN-LAST:event_mostrarBtnMouseExited

    private void vaciarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciarBtnMouseEntered
        vaciarBc.setBackground(new Color(102,102,255));
        vaciarBtn.setForeground(Color.black);
    }//GEN-LAST:event_vaciarBtnMouseEntered

    private void vaciarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciarBtnMouseExited
        vaciarBc.setBackground(new Color(51,51,255));
        vaciarBtn.setForeground(Color.white);
    }//GEN-LAST:event_vaciarBtnMouseExited

    private void ingresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseClicked
        try {
            int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el dato a ingresar"));
            cola.ingresar(dato);
        }catch(NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_ingresarBtnMouseClicked

    private void extraerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseClicked
        cola.extraer();
    }//GEN-LAST:event_extraerBtnMouseClicked

    private void mostrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseClicked
        cola.mostrarCola();
    }//GEN-LAST:event_mostrarBtnMouseClicked

    private void vaciarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciarBtnMouseClicked
        cola.vaciarCola();
        JOptionPane.showMessageDialog(this,"La cola se ha vaciado");          


    }//GEN-LAST:event_vaciarBtnMouseClicked

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        JOptionPane.showMessageDialog(this,"COLA SIMPLE\n"
            + "   Métodos\n"
            + "       Ingresar dato -> Ingresa un dato a la cola\n"
            + "       Extraer dato -> Extraer y eliminara el primer elemento de la cola\n"
            + "       Mostrar pila -> Muestra en pantalla la cola\n"
            + "       Cola vacia -> Muestra en pantalla si la cola esta vacia o no\n"
            + " **Esta cola solo admite números enteros, cualquier otro tipo de dato no será tomado en cuenta**\n");
    }//GEN-LAST:event_infoBtnMouseClicked

    private void infoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseEntered
        infoBc.setBackground(new Color(102,102,255));
        infoBtn.setForeground(Color.black);
    }//GEN-LAST:event_infoBtnMouseEntered

    private void infoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseExited
        infoBc.setBackground(new Color(51,51,255));
        infoBtn.setForeground(Color.white);
    }//GEN-LAST:event_infoBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel extraerBc;
    private javax.swing.JLabel extraerBtn;
    private javax.swing.JPanel infoBc;
    private javax.swing.JLabel infoBtn;
    private javax.swing.JPanel ingresarBc;
    private javax.swing.JLabel ingresarBtn;
    private javax.swing.JPanel mostrarBc;
    private javax.swing.JLabel mostrarBtn;
    private javax.swing.JPanel vaciarBc;
    private javax.swing.JLabel vaciarBtn;
    // End of variables declaration//GEN-END:variables
}
