/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 *
 *
    https://github.com/chuyrc/EstructurasGUI.git
 */
package gui;

import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author chuy
 */
public class PanelCP extends javax.swing.JPanel {

    LinkedList<Integer> cola = new LinkedList();
    
    public PanelCP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarBc = new javax.swing.JPanel();
        ingresarBtn = new javax.swing.JLabel();
        extraerBc = new javax.swing.JPanel();
        extraerBtn = new javax.swing.JLabel();
        tamañoBc = new javax.swing.JPanel();
        tamañoBtn = new javax.swing.JLabel();
        primerBc = new javax.swing.JPanel();
        primerBtn = new javax.swing.JLabel();
        ultimoBc = new javax.swing.JPanel();
        ultimoBtn = new javax.swing.JLabel();
        limpiarBc = new javax.swing.JPanel();
        limpiarBtn = new javax.swing.JLabel();
        infoBc = new javax.swing.JPanel();
        infoBtn = new javax.swing.JLabel();
        mostrarBc = new javax.swing.JPanel();
        mostrarBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 255));

        ingresarBc.setBackground(new java.awt.Color(51, 51, 255));

        ingresarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        ingresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ingresarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresarBtn.setText("Ingresar dato");
        ingresarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresarBcLayout = new javax.swing.GroupLayout(ingresarBc);
        ingresarBc.setLayout(ingresarBcLayout);
        ingresarBcLayout.setHorizontalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        ingresarBcLayout.setVerticalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        extraerBc.setBackground(new java.awt.Color(51, 51, 255));

        extraerBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        extraerBtn.setForeground(new java.awt.Color(255, 255, 255));
        extraerBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extraerBtn.setText("Extraer dato");
        extraerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extraerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extraerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extraerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extraerBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extraerBcLayout = new javax.swing.GroupLayout(extraerBc);
        extraerBc.setLayout(extraerBcLayout);
        extraerBcLayout.setHorizontalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraerBcLayout.createSequentialGroup()
                .addComponent(extraerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        extraerBcLayout.setVerticalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extraerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        tamañoBc.setBackground(new java.awt.Color(51, 51, 255));

        tamañoBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        tamañoBtn.setForeground(new java.awt.Color(255, 255, 255));
        tamañoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamañoBtn.setText("Tamaño");
        tamañoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tamañoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamañoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tamañoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tamañoBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tamañoBcLayout = new javax.swing.GroupLayout(tamañoBc);
        tamañoBc.setLayout(tamañoBcLayout);
        tamañoBcLayout.setHorizontalGroup(
            tamañoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamañoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        tamañoBcLayout.setVerticalGroup(
            tamañoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamañoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        primerBc.setBackground(new java.awt.Color(51, 51, 255));

        primerBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        primerBtn.setForeground(new java.awt.Color(255, 255, 255));
        primerBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primerBtn.setText("Primer elemento");
        primerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        primerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                primerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                primerBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout primerBcLayout = new javax.swing.GroupLayout(primerBc);
        primerBc.setLayout(primerBcLayout);
        primerBcLayout.setHorizontalGroup(
            primerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        primerBcLayout.setVerticalGroup(
            primerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        ultimoBc.setBackground(new java.awt.Color(51, 51, 255));

        ultimoBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        ultimoBtn.setForeground(new java.awt.Color(255, 255, 255));
        ultimoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ultimoBtn.setText("Ultimo elemento");
        ultimoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ultimoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ultimoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ultimoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ultimoBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ultimoBcLayout = new javax.swing.GroupLayout(ultimoBc);
        ultimoBc.setLayout(ultimoBcLayout);
        ultimoBcLayout.setHorizontalGroup(
            ultimoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ultimoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        ultimoBcLayout.setVerticalGroup(
            ultimoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ultimoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        limpiarBc.setBackground(new java.awt.Color(51, 51, 255));

        limpiarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        limpiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limpiarBtn.setText("Limpiar cola");
        limpiarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout limpiarBcLayout = new javax.swing.GroupLayout(limpiarBc);
        limpiarBc.setLayout(limpiarBcLayout);
        limpiarBcLayout.setHorizontalGroup(
            limpiarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limpiarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        limpiarBcLayout.setVerticalGroup(
            limpiarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        infoBc.setBackground(new java.awt.Color(51, 51, 255));

        infoBtn.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        infoBtn.setForeground(new java.awt.Color(255, 255, 255));
        infoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoBtn.setText("?");
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout infoBcLayout = new javax.swing.GroupLayout(infoBc);
        infoBc.setLayout(infoBcLayout);
        infoBcLayout.setHorizontalGroup(
            infoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        infoBcLayout.setVerticalGroup(
            infoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mostrarBc.setBackground(new java.awt.Color(51, 51, 255));

        mostrarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        mostrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        mostrarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarBtn.setText("Mostrar cola");
        mostrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostrarBcLayout = new javax.swing.GroupLayout(mostrarBc);
        mostrarBc.setLayout(mostrarBcLayout);
        mostrarBcLayout.setHorizontalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        mostrarBcLayout.setVerticalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(primerBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(ultimoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tamañoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingresarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(extraerBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mostrarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addComponent(infoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(limpiarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(infoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ingresarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(extraerBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ultimoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primerBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tamañoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(limpiarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseEntered
        ingresarBc.setBackground(new Color(102,102,255));
        ingresarBtn.setForeground(Color.black);
    }//GEN-LAST:event_ingresarBtnMouseEntered

    private void ingresarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseExited
        ingresarBc.setBackground(new Color(51,51,255));
        ingresarBtn.setForeground(Color.white);
    }//GEN-LAST:event_ingresarBtnMouseExited

    private void extraerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseEntered
        extraerBc.setBackground(new Color(102,102,255));
        extraerBtn.setForeground(Color.black);
    }//GEN-LAST:event_extraerBtnMouseEntered

    private void extraerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseExited
        extraerBc.setBackground(new Color(51,51,255));
        extraerBtn.setForeground(Color.white);
    }//GEN-LAST:event_extraerBtnMouseExited

    private void tamañoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamañoBtnMouseEntered
        tamañoBc.setBackground(new Color(102,102,255));
        tamañoBtn.setForeground(Color.black);
    }//GEN-LAST:event_tamañoBtnMouseEntered

    private void tamañoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamañoBtnMouseExited
        tamañoBc.setBackground(new Color(51,51,255));
        tamañoBtn.setForeground(Color.white);
    }//GEN-LAST:event_tamañoBtnMouseExited

    private void ingresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseClicked
        try {
            cola.add(Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese el dato")));
            JOptionPane.showMessageDialog(this,"Se ingreso el dato con exito");
        }catch(NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_ingresarBtnMouseClicked

    private void extraerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseClicked
        if(cola.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La cola esta vacia");         
            return;
        }
        int a = cola.remove();             
        JOptionPane.showMessageDialog(this,"Se ha extraido el elemento" + a);
    }//GEN-LAST:event_extraerBtnMouseClicked

    private void tamañoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamañoBtnMouseClicked
        JOptionPane.showMessageDialog(this,"El tamaño de la cola es: " + cola.size());
    }//GEN-LAST:event_tamañoBtnMouseClicked

    private void infoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseClicked
        JOptionPane.showMessageDialog(this,"LINKEDLIST (cola)\n"
            + "   Métodos\n"
            + "       Ingresar dato -> Ingresa un dato a la cola\n"
            + "       Extraer -> Extrae el primer elemento de la lista\n"
            + "       Primer elemento -> Muestra el elemento de la cola\n"
            + "       Ultimo dato -> Muestra el ultimo elemento de la cola\n"
            + "       Tamaño -> Muestra el tamaño de la cola (números de elementos)\n"
            + "       Limpiar cola -> Vacia todos los elementos de la cola\n"
            + "       Ver cola -> Muestra la cola\n"
            + " **Este LinkedList es de tipo Integer por lo que solo admite números enteros,\n cualquier otro tipo de dato no será tomado en cuenta**\n");
    }//GEN-LAST:event_infoBtnMouseClicked
    
    private void infoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseEntered
        infoBc.setBackground(new Color(102,102,255));
        infoBtn.setForeground(Color.black);
    }//GEN-LAST:event_infoBtnMouseEntered

    private void infoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoBtnMouseExited
        infoBc.setBackground(new Color(51,51,255));
        infoBtn.setForeground(Color.white);
    }//GEN-LAST:event_infoBtnMouseExited

    private void limpiarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarBtnMouseExited
        limpiarBc.setBackground(new Color(51,51,255));
        limpiarBtn.setForeground(Color.white);
    }//GEN-LAST:event_limpiarBtnMouseExited

    private void limpiarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarBtnMouseEntered
        limpiarBc.setBackground(new Color(102,102,255));
        limpiarBtn.setForeground(Color.black);
    }//GEN-LAST:event_limpiarBtnMouseEntered

    private void limpiarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarBtnMouseClicked
        cola.clear();
        JOptionPane.showMessageDialog(this,"Se ha vaciado la cola");
    }//GEN-LAST:event_limpiarBtnMouseClicked

    private void primerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primerBtnMouseExited
        primerBc.setBackground(new Color(51,51,255));
        primerBtn.setForeground(Color.white);
    }//GEN-LAST:event_primerBtnMouseExited

    private void primerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primerBtnMouseEntered
        primerBc.setBackground(new Color(102,102,255));
        primerBtn.setForeground(Color.black);
    }//GEN-LAST:event_primerBtnMouseEntered

    private void primerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primerBtnMouseClicked
        if(cola.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La lista esta vacia");
            return;
        }
        int a = cola.getFirst();
        JOptionPane.showMessageDialog(null,"El primer elemento es: " + a);
    }//GEN-LAST:event_primerBtnMouseClicked

    private void ultimoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ultimoBtnMouseExited
        ultimoBc.setBackground(new Color(51,51,255));
        ultimoBtn.setForeground(Color.white);
    }//GEN-LAST:event_ultimoBtnMouseExited

    private void ultimoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ultimoBtnMouseEntered
        ultimoBc.setBackground(new Color(102,102,255));
        ultimoBtn.setForeground(Color.black);
    }//GEN-LAST:event_ultimoBtnMouseEntered

    private void ultimoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ultimoBtnMouseClicked
        if(cola.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La cola esta vacia");
            return;
        }
        int a = cola.getLast();
        JOptionPane.showMessageDialog(null,"El ultimo elemento es: " + a);
    }//GEN-LAST:event_ultimoBtnMouseClicked

    private void mostrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseClicked
        if(cola.isEmpty()) {
            JOptionPane.showMessageDialog(this,"La cola esta vacia");
            return;
        }
        String lista = "";
        String listaInvertida = "";
        
        for(int dato : cola) {
            lista += "  " + dato + "\n";
        }
        String[] cadena  = lista.split(" ");
        
        for(int i = cadena.length - 1; i >= 0; i--) {
                listaInvertida += "" + cadena[i];
        }
        JOptionPane.showMessageDialog(null,"Cola\n" + listaInvertida);
    }//GEN-LAST:event_mostrarBtnMouseClicked

    private void mostrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseEntered
        mostrarBc.setBackground(new Color(102,102,255));
        mostrarBtn.setForeground(Color.black);
    }//GEN-LAST:event_mostrarBtnMouseEntered

    private void mostrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseExited
        mostrarBc.setBackground(new Color(51,51,255));
        mostrarBtn.setForeground(Color.white);
    }//GEN-LAST:event_mostrarBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel extraerBc;
    private javax.swing.JLabel extraerBtn;
    private javax.swing.JPanel infoBc;
    private javax.swing.JLabel infoBtn;
    private javax.swing.JPanel ingresarBc;
    private javax.swing.JLabel ingresarBtn;
    private javax.swing.JPanel limpiarBc;
    private javax.swing.JLabel limpiarBtn;
    private javax.swing.JPanel mostrarBc;
    private javax.swing.JLabel mostrarBtn;
    private javax.swing.JPanel primerBc;
    private javax.swing.JLabel primerBtn;
    private javax.swing.JPanel tamañoBc;
    private javax.swing.JLabel tamañoBtn;
    private javax.swing.JPanel ultimoBc;
    private javax.swing.JLabel ultimoBtn;
    // End of variables declaration//GEN-END:variables
}
