/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import estructuras.Pila;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author chuy
 */
public class PanelPS extends javax.swing.JPanel {

    Pila pila = new Pila();
    
    public PanelPS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarBc = new javax.swing.JPanel();
        ingresarBtn = new javax.swing.JLabel();
        extraerBc = new javax.swing.JPanel();
        extraerBtn = new javax.swing.JLabel();
        topeBc = new javax.swing.JPanel();
        topeBtn = new javax.swing.JLabel();
        tamanoBc = new javax.swing.JPanel();
        tamanoBtn = new javax.swing.JLabel();
        vaciarBc = new javax.swing.JPanel();
        vaciarBtn = new javax.swing.JLabel();
        mostrarBc = new javax.swing.JPanel();
        mostrarBtn = new javax.swing.JLabel();
        vaciaBc = new javax.swing.JPanel();
        vaciaBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        ingresarBc.setBackground(new java.awt.Color(51, 51, 255));

        ingresarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        ingresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ingresarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresarBtn.setText("Ingresar dato");
        ingresarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresarBcLayout = new javax.swing.GroupLayout(ingresarBc);
        ingresarBc.setLayout(ingresarBcLayout);
        ingresarBcLayout.setHorizontalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        ingresarBcLayout.setVerticalGroup(
            ingresarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        extraerBc.setBackground(new java.awt.Color(51, 51, 255));

        extraerBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        extraerBtn.setForeground(new java.awt.Color(255, 255, 255));
        extraerBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extraerBtn.setText("Extraer dato");
        extraerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extraerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extraerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extraerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extraerBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extraerBcLayout = new javax.swing.GroupLayout(extraerBc);
        extraerBc.setLayout(extraerBcLayout);
        extraerBcLayout.setHorizontalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraerBcLayout.createSequentialGroup()
                .addComponent(extraerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        extraerBcLayout.setVerticalGroup(
            extraerBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extraerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        topeBc.setBackground(new java.awt.Color(51, 51, 255));

        topeBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        topeBtn.setForeground(new java.awt.Color(255, 255, 255));
        topeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topeBtn.setText("Mostrar Tope");
        topeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout topeBcLayout = new javax.swing.GroupLayout(topeBc);
        topeBc.setLayout(topeBcLayout);
        topeBcLayout.setHorizontalGroup(
            topeBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topeBcLayout.setVerticalGroup(
            topeBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tamanoBc.setBackground(new java.awt.Color(51, 51, 255));

        tamanoBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        tamanoBtn.setForeground(new java.awt.Color(255, 255, 255));
        tamanoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamanoBtn.setText("Tamaño");
        tamanoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tamanoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamanoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tamanoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tamanoBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tamanoBcLayout = new javax.swing.GroupLayout(tamanoBc);
        tamanoBc.setLayout(tamanoBcLayout);
        tamanoBcLayout.setHorizontalGroup(
            tamanoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamanoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tamanoBcLayout.setVerticalGroup(
            tamanoBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamanoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        vaciarBc.setBackground(new java.awt.Color(51, 51, 255));

        vaciarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        vaciarBtn.setForeground(new java.awt.Color(255, 255, 255));
        vaciarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaciarBtn.setText("Vaciar pila");
        vaciarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vaciarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaciarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vaciarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vaciarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout vaciarBcLayout = new javax.swing.GroupLayout(vaciarBc);
        vaciarBc.setLayout(vaciarBcLayout);
        vaciarBcLayout.setHorizontalGroup(
            vaciarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaciarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vaciarBcLayout.setVerticalGroup(
            vaciarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaciarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mostrarBc.setBackground(new java.awt.Color(51, 51, 255));

        mostrarBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        mostrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        mostrarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarBtn.setText("Mostrar pila");
        mostrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostrarBcLayout = new javax.swing.GroupLayout(mostrarBc);
        mostrarBc.setLayout(mostrarBcLayout);
        mostrarBcLayout.setHorizontalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        mostrarBcLayout.setVerticalGroup(
            mostrarBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarBcLayout.createSequentialGroup()
                .addComponent(mostrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        vaciaBc.setBackground(new java.awt.Color(51, 51, 255));

        vaciaBtn.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        vaciaBtn.setForeground(new java.awt.Color(255, 255, 255));
        vaciaBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vaciaBtn.setText("Pila vacia");
        vaciaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vaciaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vaciaBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vaciaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vaciaBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout vaciaBcLayout = new javax.swing.GroupLayout(vaciaBc);
        vaciaBc.setLayout(vaciaBcLayout);
        vaciaBcLayout.setHorizontalGroup(
            vaciaBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaciaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        vaciaBcLayout.setVerticalGroup(
            vaciaBcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vaciaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vaciarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topeBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ingresarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(extraerBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tamanoBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostrarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(vaciaBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extraerBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topeBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tamanoBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vaciarBc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrarBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(vaciaBc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseEntered
        ingresarBc.setBackground(new Color(102,102,255));
        ingresarBtn.setForeground(Color.black);
    }//GEN-LAST:event_ingresarBtnMouseEntered

    private void ingresarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseExited
        ingresarBc.setBackground(new Color(51,51,255));
        ingresarBtn.setForeground(Color.white);
    }//GEN-LAST:event_ingresarBtnMouseExited

    private void extraerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseEntered
        extraerBc.setBackground(new Color(102,102,255));
        extraerBtn.setForeground(Color.black);
    }//GEN-LAST:event_extraerBtnMouseEntered

    private void extraerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseExited
        extraerBc.setBackground(new Color(51,51,255));
        extraerBtn.setForeground(Color.white);
    }//GEN-LAST:event_extraerBtnMouseExited

    private void topeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topeBtnMouseEntered
        topeBc.setBackground(new Color(102,102,255));
        topeBtn.setForeground(Color.black);
    }//GEN-LAST:event_topeBtnMouseEntered

    private void topeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topeBtnMouseExited
        topeBc.setBackground(new Color(51,51,255));
        topeBtn.setForeground(Color.white);
    }//GEN-LAST:event_topeBtnMouseExited

    private void tamanoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanoBtnMouseEntered
        tamanoBc.setBackground(new Color(102,102,255));
        tamanoBtn.setForeground(Color.black);
    }//GEN-LAST:event_tamanoBtnMouseEntered

    private void tamanoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanoBtnMouseExited
        tamanoBc.setBackground(new Color(51,51,255));
        tamanoBtn.setForeground(Color.white);
    }//GEN-LAST:event_tamanoBtnMouseExited

    private void vaciarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciarBtnMouseEntered
        vaciarBc.setBackground(new Color(102,102,255));
        vaciarBtn.setForeground(Color.black);
    }//GEN-LAST:event_vaciarBtnMouseEntered

    private void vaciarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciarBtnMouseExited
        vaciarBc.setBackground(new Color(51,51,255));
        vaciarBtn.setForeground(Color.white);
    }//GEN-LAST:event_vaciarBtnMouseExited

    private void mostrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseEntered
        mostrarBc.setBackground(new Color(102,102,255));
        mostrarBtn.setForeground(Color.black);
    }//GEN-LAST:event_mostrarBtnMouseEntered

    private void mostrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseExited
        mostrarBc.setBackground(new Color(51,51,255));
        mostrarBtn.setForeground(Color.white);
    }//GEN-LAST:event_mostrarBtnMouseExited

    private void ingresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarBtnMouseClicked
        try {
            int dato = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el dato a ingresar"));
            pila.ingresar(dato);
        }catch(NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_ingresarBtnMouseClicked

    private void extraerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extraerBtnMouseClicked
        //if(pila.extraer() != null) {
        try {
            int datoExtraido = pila.extraer();
            JOptionPane.showMessageDialog(this,"Se obtuvo el dato con exito");
        }catch(NullPointerException e) {
            JOptionPane.showMessageDialog(this,"La pila esta vacia");
            return;
        }
        //}
    }//GEN-LAST:event_extraerBtnMouseClicked

    private void topeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topeBtnMouseClicked
        if(pila.mostrarTope() != null) {
            int tope = pila.mostrarTope();
            JOptionPane.showMessageDialog(this,"El tope de la pila es: " + tope);
        }else {
            JOptionPane.showMessageDialog(this,"La pila esta vacia");
        }
        
    }//GEN-LAST:event_topeBtnMouseClicked

    private void tamanoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamanoBtnMouseClicked
        JOptionPane.showMessageDialog(this,"El tamaño de la pila es: " + pila.getTamano());
    }//GEN-LAST:event_tamanoBtnMouseClicked

    private void vaciarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciarBtnMouseClicked
        pila.vaciarPila();
        JOptionPane.showMessageDialog(this,"Se ha vaciado la pila");
    }//GEN-LAST:event_vaciarBtnMouseClicked

    private void mostrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseClicked
        pila.mostrarPila();
    }//GEN-LAST:event_mostrarBtnMouseClicked

    private void vaciaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciaBtnMouseEntered
        vaciaBc.setBackground(new Color(102,102,255));
        vaciaBtn.setForeground(Color.black);
    }//GEN-LAST:event_vaciaBtnMouseEntered

    private void vaciaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciaBtnMouseExited
        vaciaBc.setBackground(new Color(51,51,255));
        vaciaBtn.setForeground(Color.white);
    }//GEN-LAST:event_vaciaBtnMouseExited

    private void vaciaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vaciaBtnMouseClicked
        if(pila.pilaVacia()) {
            JOptionPane.showMessageDialog(this,"La pila esta vacia");
            return;
        }
        JOptionPane.showMessageDialog(this,"La pila no esta vacia");
    }//GEN-LAST:event_vaciaBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel extraerBc;
    private javax.swing.JLabel extraerBtn;
    private javax.swing.JPanel ingresarBc;
    private javax.swing.JLabel ingresarBtn;
    private javax.swing.JPanel mostrarBc;
    private javax.swing.JLabel mostrarBtn;
    private javax.swing.JPanel tamanoBc;
    private javax.swing.JLabel tamanoBtn;
    private javax.swing.JPanel topeBc;
    private javax.swing.JLabel topeBtn;
    private javax.swing.JPanel vaciaBc;
    private javax.swing.JLabel vaciaBtn;
    private javax.swing.JPanel vaciarBc;
    private javax.swing.JLabel vaciarBtn;
    // End of variables declaration//GEN-END:variables
}
